### ISSUE TITLE
Can't compile in xcode

### ISSUE THREAD

**Issue by kerinzeebart** [andrewnakas/ARKit-Cardboard-VR#3]
Hi,
Tried your code but get errors on Semantic Issue Undeclared selector 'setDisplaySyncEnabled:'

**Comment by europeanrich** [comment]
Tested and working in Xcode Beta 5 with Unity 2017.10f3 running iOS 11 Beta 5. 
Only need to change one line, otherwise will crash on start.

in the file "ARSessionNative.mm" located in the Plugins/iOS/UnityARKit/NativeInterface, replace:

`s_CurAffineTransform = [frame displayTransformWithViewportSize:nativeSize orientation:[[UIApplication sharedApplication] statusBarOrientation]];
`

with

`s_CurAffineTransform = [frame displayTransformForOrientation:[[UIApplication sharedApplication] statusBarOrientation] viewportSize:nativeSize];`

(thanks to Scale1Portal on the Unity-ARKit-Plugin forum for this fix)

**Comment by andrewnakas** [comment]
Hmm yah I saw that Xcode one line fix after I updated to beta 5 and all my arkit demos broke. 

Thanks for posting this! P.S I'll probs look into making this better once the release candidate sdk comes around.
